default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hotdealsfinda_development

test:
  <<: *default
  database: hotdealsfinda_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: hotdealsfinda_production
  username: hotdealsfinda
  password: <%= Rails.application.credentials.production[:db][:password] %>
  host: localhost
  port: <%= Rails.application.credentials.production[:db][:port] %>
