# aws:
#   access_key_id: 123
#   secret_access_key: 345

production:
  db:
    password: ark2DMN6%QHW
    host: hello-world.c12jtixxzya2.us-east-2.rds.amazonaws.com
    port: 5432

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: 7598465582a6805fcf4555215eac3e6eba0de690356e532b19365c8f1ca8e77739fca5890a28eb9d3ee1aaf00370050b0a70b2dd644da8ab200fd610c60d23be
